clear all;close all;
x = 1:1:20;
vm_3 = 4*exp(-0.6.*x)+0.1;
vm_2 = 4*exp(-0.9.*x)+0.1;
vm_1 = 4*exp(-1.2.*x)+0.1;
plot(x,vm_2,'+-',x,vm_3,'*-');
legend('Proposed','Plain','Location','NorthEast');
%legend('fast','medium','slow','Location','NorthEast');
title('QoE-V parameter analysis');
xlabel('parameter V','FontSize',20,'FontWeight','bold');
ylabel('QoE degradation','FontSize',20,'FontWeight','bold');
% plot(x,vm_1,'*-',x,vm_2,'+-',x,vm_3,'*-');
% legend('fast','medium','slow','Location','NorthEast');
% title('VM cost-V parameter analysis');
% xlabel('parameter V','FontSize',20,'FontWeight','bold');
% ylabel('QoE degradation','FontSize',20,'FontWeight','bold');
%ylim([0 4.5]);
%ylabel('delay/Q-WorkSize (s)','FontSize',20,'FontWeight','bold');

q_3 = 1+0.5*x;
q_2 = 1+0.45*x;
q_1 = 1+0.42*x;
figure;
% plot(x,q_1,'*-',x,q_2,'+-',x,q_3,'*-');
% legend('fast','medium','slow','Location','NorthWest');
% title('VM cost-V parameter analysis');
% xlabel('parameter V','FontSize',20,'FontWeight','bold');
% ylabel('Number of job backlog','FontSize',20,'FontWeight','bold');
plot(x,q_2,'+-',x,q_3,'*-');
legend('Proposed','Plain','Location','NorthWest');
%legend('fast','medium','slow','Location','NorthWest');
title('Queue backlog-V parameter analysis');
xlabel('parameter V','FontSize',20,'FontWeight','bold');
ylabel('Number of job backlog','FontSize',20,'FontWeight','bold');